"""
Strategy Critic — second-LLM code review before backtest.

Why this exists: of the recent generations, 11 of 14 strategies hit 0 trades
in backtest because the LLM combined too many filter conditions or used
thresholds that were never simultaneously satisfiable. The validation_pipeline
catches mechanical issues (banned imports, look-ahead via .shift(-N), missing
methods). The critic catches *judgment* issues a careful reader would flag:

  - Over-constrained entries (too many AND conditions → guaranteed 0 trades)
  - Missing NaN guards on external columns (fgi / vix / btc_funding_rate etc.
    can be NaN on early candles and silently zero out the whole entry signal)
  - Regime/logic mismatch (TARGET_REGIME="trending" but the logic is a fade)
  - Threshold values that don't make physical sense
  - Subtle look-ahead patterns the AST validator misses

The critic returns structured JSON so the generator can either retry (REJECT)
or proceed with a note (WARN/PASS). If the critic call itself errors, the
generator proceeds as if PASS — the critic must never block on its own bugs.
"""

import json
import logging
import os
import re
from typing import Any

log = logging.getLogger("strategy_critic")


CRITIC_SYSTEM_PROMPT = """You are a senior code reviewer for Freqtrade trading strategies generated by another LLM.
Your job is to catch judgment errors that mechanical validators miss — over-constrained logic, missing NaN guards on external data, regime/logic mismatches, fragile thresholds, subtle look-ahead.

You do NOT rewrite the code. You return ONE JSON object with this exact shape:

{
  "verdict": "PASS" | "WARN" | "REJECT",
  "summary": "one short sentence",
  "issues": [
    {"severity": "high" | "medium" | "low",
     "category": "overfit" | "nan-guard" | "regime-mismatch" | "look-ahead" | "threshold" | "other",
     "description": "specific issue and why it matters"}
  ]
}

Verdict rules:
  REJECT — at least one high-severity issue that will almost certainly produce
           0 trades or look-ahead bias. Examples: 7+ AND conditions in entry,
           reading external columns without NaN guards in the entry expression,
           comparing dataframe['rsi'] (0-100) against a threshold like 250.
  WARN   — medium-severity issues that may hurt but won't necessarily kill
           the strategy. Strategy proceeds to backtest with the warning logged.
  PASS   — no significant issues. Strategy proceeds normally.

Specific things to flag as HIGH severity:

1. ENTRY HAS 6+ AND CONDITIONS
   With 6 independent filters each firing ~20% of the time, the joint probability
   is 0.2^6 = 0.0064% — essentially never. This is the #1 cause of 0-trade
   strategies in our data. Count the number of `&` joining boolean Series in the
   `dataframe.loc[...]` expression of populate_entry_trend.

2. EXTERNAL COLUMN USED WITHOUT NAN GUARD
   The columns from add_external_data (fgi, vix, gold, dxy, spx, btc_funding_rate,
   btc_oi, btc_oi_pct_change_24h) can be NaN on early candles or when the
   macro feed hasn't run. Any comparison like `dataframe['vix'] < 20` in an
   entry condition will produce NaN, which evaluates as False in a boolean
   AND — silently killing the signal. Required pattern is either
   `.fillna(default)` or wrapping in `& dataframe['vix'].notna()`.

3. REGIME/LOGIC MISMATCH
   TARGET_REGIME="trending" but populate_entry_trend looks like mean-reversion
   (e.g., RSI < oversold OR price < lower BB). The orchestrator routes
   strategies by their TARGET_REGIME, so a mismatch means the strategy runs
   in conditions it wasn't designed for.

4. LOOK-AHEAD NOT CAUGHT BY AST
   For example: using `dataframe['close']` directly in an entry on the same
   bar (without `.shift(1)`) when the strategy is meant to react to a
   "completed" candle. Or comparing today's high to today's resistance level
   that was computed using today's high.

5. THRESHOLD SANITY
   RSI compared to a value outside 0-100, %B compared outside 0-1, funding
   rate against values outside -0.005 to +0.005 (50bp / 8h is already extreme).

   IMPORTANT — fgi is project-specific, NOT the public 0-100 Alternative.me
   index. Empirical range on real data: roughly -22 to +45, median ~5, std ~12.
   - fgi < 0     fires ~45% of days   (NOT "always false" — common valid filter)
   - fgi < -10   fires ~10% of days   (strong fear, sharp contrarian signal)
   - fgi > 20    fires ~10% of days   (strong greed)
   - fgi < -50, fgi > 50, fgi > 70, fgi < 0 || > 100 — ANY threshold treating
     fgi as 0-100 IS the bug; flag it as such. But never flag fgi < 0,
     fgi < -10, or fgi > 20 as impossible — those are correct usage.

You output ONLY the JSON object. No prose, no markdown fences."""


def critic_review(
    code: str,
    model: str | None = None,
    provider: str | None = None,
) -> dict:
    """Run the critic on a strategy source string. Returns the parsed JSON.

    `model` / `provider` are forwarded to llm_client.chat_completion. When None,
    the env-driven defaults apply (same as the generator).

    On any error (no API key, transport failure, malformed response), returns
    a synthetic PASS verdict with `error` set — the generator MUST treat critic
    failures as non-blocking. We never want the critic itself to halt the
    pipeline; its job is to add signal, not gate.
    """
    # Lazy import — keeps llm_client out of test paths that fully mock the
    # critic. Importing here also ensures we pick up monkeypatched modules.
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from llm_client import chat_completion

    user_prompt = f"Review this Freqtrade strategy:\n\n```python\n{code}\n```"

    try:
        # 4096 because reasoning-capable models (DeepSeek V4 Pro) burn a
        # non-deterministic 30-300 tokens on internal reasoning_content
        # BEFORE emitting the visible JSON. 2048 worked most of the time
        # but live trials caught occasional truncation mid-reasoning,
        # leaving no JSON in the output and a synthetic-PASS fallback that
        # silently strips the critic's value. 4096 gives comfortable
        # headroom for ~500 tokens of reasoning + a verbose REJECT verdict
        # with several issues.
        text = chat_completion(
            messages=[{"role": "user", "content": user_prompt}],
            system=CRITIC_SYSTEM_PROMPT,
            model=model,
            max_tokens=4096,
            provider=provider,
        )
    except Exception as e:
        log.warning(f"Critic API call failed: {e}")
        return {"verdict": "PASS",
                "summary": f"critic skipped (api error: {e})",
                "issues": [], "error": str(e)}

    return _parse_verdict_json(text)


def _parse_verdict_json(text: str) -> dict:
    """Extract the JSON object from the critic response. Tolerates accidental
    markdown fences. Returns a synthetic PASS with error= if parsing fails.
    """
    # Strip code fences if the model added them despite instructions
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    raw = fenced.group(1) if fenced else text.strip()

    # Find the outermost JSON object — balanced braces
    start = raw.find("{")
    if start == -1:
        return {"verdict": "PASS", "summary": "critic returned no JSON", "issues": [], "error": "no_json_block", "raw": text[:200]}

    depth = 0
    end = -1
    in_string = False
    escape = False
    for i in range(start, len(raw)):
        ch = raw[i]
        if escape:
            escape = False
            continue
        if ch == "\\":
            escape = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                break

    if end == -1:
        return {"verdict": "PASS", "summary": "critic returned unbalanced JSON", "issues": [], "error": "unbalanced_json", "raw": text[:200]}

    try:
        parsed: dict[str, Any] = json.loads(raw[start:end])
    except json.JSONDecodeError as e:
        return {"verdict": "PASS", "summary": f"critic JSON malformed: {e}", "issues": [], "error": "json_decode_error", "raw": text[:200]}

    # Normalize: ensure required keys exist with sensible defaults
    verdict = str(parsed.get("verdict", "PASS")).upper()
    if verdict not in ("PASS", "WARN", "REJECT"):
        verdict = "PASS"
    return {
        "verdict": verdict,
        "summary": parsed.get("summary", ""),
        "issues": parsed.get("issues", []),
    }


def format_critic_feedback(critic_result: dict) -> str:
    """Render critic issues into the regeneration prompt as natural language."""
    issues = critic_result.get("issues", [])
    if not issues:
        return critic_result.get("summary", "")
    lines = [f"Critic verdict: {critic_result.get('verdict', '?')}"]
    if critic_result.get("summary"):
        lines.append(f"Summary: {critic_result['summary']}")
    lines.append("Issues to fix:")
    for i, issue in enumerate(issues, 1):
        sev = issue.get("severity", "?").upper()
        cat = issue.get("category", "?")
        desc = issue.get("description", "")
        lines.append(f"  {i}. [{sev}/{cat}] {desc}")
    return "\n".join(lines)
